spring:
  datasource:
    url: jdbc:h2:file:/tmp/codepong;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: none

tmc:
  sandboxUrl: http://172.17.0.1:3001
  notifyUrl: http://127.0.0.1:3000/submission-result

security:
  oauth2:
    client:
      tmc:
        authorizationUri: https://tmc.mooc.fi/oauth/authorize
        tokenUri: https://tmc.mooc.fi/oauth/token
        userInfoUri: https://tmc.mooc.fi/api/v8/users/current
        redirectUri: https://pingis.testmycode.io/oauth2/authorize/code/tmc

server:
  use-forward-headers: true
